"""Convenience import: ``import dakma`` re-exports the public API from ``dakma_sdk``."""

from dakma_sdk import (
    AuditEvent,
    ComputeUsageRecorder,
    ComputeUsageSnapshot,
    DakmaClient,
    Dataset,
    Decision,
    DecisionEvent,
    DecisionOutput,
    EnrichedResult,
    Explanation,
    ExplainPayload,
    FeatureImportance,
    Model,
    ModelHandle,
    Project,
    TopFactor,
    enable_logging,
    format_audit_entry_markdown,
    format_audit_log_markdown,
    format_inference_result_markdown,
    init,
    write_audit_report,
    write_inference_report,
    write_report_file,
)

__all__ = [
    "init",
    "enable_logging",
    "DakmaClient",
    "ModelHandle",
    "ComputeUsageRecorder",
    "ComputeUsageSnapshot",
    "Project",
    "Model",
    "Dataset",
    "Decision",
    "Explanation",
    "AuditEvent",
    "DecisionEvent",
    "DecisionOutput",
    "EnrichedResult",
    "ExplainPayload",
    "FeatureImportance",
    "TopFactor",
    "format_audit_log_markdown",
    "format_audit_entry_markdown",
    "format_inference_result_markdown",
    "write_audit_report",
    "write_inference_report",
    "write_report_file",
]
